version: '3'

services: 
    books-service:
        build: "books-service"
        depends_on: 
            - mysql
        ports: 
            - "5000:5000"
        restart: on-failure
        env_file: 
            - db.env
    
    users-service:
        build: "users-service"
        depends_on: 
            - mysql
        ports: 
            - "5001:5001"
        restart: on-failure
        env_file: db.env

    login-service:
        build: "login-service"
        depends_on: 
            - mysql
        ports: 
            - "5003:5003"
        restart: on-failure
        env_file: db.env

    library-service:
        build: library-service
        depends_on: 
            - mysql
        ports:
            - "5002:5002"
        restart: on-failure
        env_file: db.env
            # - db.env
            # - library-service/conf.env
        environment:
            - "UsersServiceURL=http://users-service:5001"
            - "BooksServiceURL=http://books-service:5000"

    mysql:
        image: "mysql:latest"
        ports: 
            - "3307:3306"
        volumes: 
            - ./datadump.sql:/docker-entrypoint-initdb.d/datadump.sql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"

    
